# Generated by Django 6.0.1 on 2026-01-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
