# Generated by Django 5.2.10 on 2026-01-24 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Meat', 'Meat'), ('Vegetables', 'Vegetables'), ('Leafy', 'Leafy'), ('Millets', 'Millets'), ('Cereals', 'Cereals'), ('Eggs', 'Eggs')], max_length=50)),
                ('unit', models.CharField(choices=[('gram', 'gram'), ('kilogram', 'kilogram'), ('piece', 'piece'), ('dozen', 'dozen'), ('pieces', 'pieces'), ('box', 'box'), ('ml', 'ml'), ('litre', 'litre'), ('bunch', 'bunch')], max_length=10)),
                ('quantity', models.IntegerField()),
                ('variant', models.CharField(choices=[('organic', 'organic'), ('regular', 'regular'), ('fresh', 'fresh'), ('natural', 'natural'), ('hybrid', 'hybrid')], max_length=15)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=7)),
                ('original_price', models.DecimalField(decimal_places=2, max_digits=7)),
                ('stock_quantity', models.IntegerField()),
                ('harvest_date', models.DateField()),
                ('expiry', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='products/')),
            ],
        ),
    ]
