 const data = [
  {
    id: 1,
    name: "Fresh Organic Tomatoes",
    category: "vegetables",
    unit: "500g",
    variant: "Organic",
    pricePerUnit: 120,
    originalPrice: 180,
    stockQuantity: 45,
    harvestDate: "2026-01-18",
    expiry: "2026-01-28",
    nameSeller: "Green Valley Farms",
    typeSeller: "Certified Organic Farmer",
    image: "🍅",
    description: "Fresh, juicy organic tomatoes grown without pesticides."
  },
  {
    id: 2,
    name: "Farm Fresh Potatoes",
    category: "vegetables",
    unit: "1kg",
    variant: "Regular",
    pricePerUnit: 60,
    originalPrice: 90,
    stockQuantity: 100,
    harvestDate: "2026-01-15",
    expiry: "2026-02-15",
    nameSeller: "Harvest Hub",
    typeSeller: "Local Farmer",
    image: "🥔",
    description: "Starchy and versatile potatoes perfect for everyday cooking."
  },
  {
    id: 3,
    name: "Organic Carrots",
    category: "vegetables",
    unit: "500g",
    variant: "Organic",
    pricePerUnit: 70,
    originalPrice: 100,
    stockQuantity: 60,
    harvestDate: "2026-01-17",
    expiry: "2026-02-05",
    nameSeller: "Nature Roots",
    typeSeller: "Organic Farm",
    image: "🥕",
    description: "Crunchy carrots rich in beta-carotene."
  },
  {
    id: 4,
    name: "Green Capsicum",
    category: "vegetables",
    unit: "500g",
    variant: "Fresh",
    pricePerUnit: 90,
    originalPrice: 130,
    stockQuantity: 40,
    harvestDate: "2026-01-19",
    expiry: "2026-01-30",
    nameSeller: "Fresh Basket",
    typeSeller: "Vegetable Supplier",
    image: "🫑",
    description: "Crisp green capsicum ideal for stir-fries."
  },
  {
    id: 5,
    name: "Organic Spinach",
    category: "leafy",
    unit: "250g",
    variant: "Organic",
    pricePerUnit: 40,
    originalPrice: 60,
    stockQuantity: 80,
    harvestDate: "2026-01-20",
    expiry: "2026-01-25",
    nameSeller: "Leafy Greens Co.",
    typeSeller: "Organic Farmer",
    image: "🥬",
    description: "Iron-rich spinach freshly harvested."
  },
  {
    id: 6,
    name: "Fresh Coriander Leaves",
    category: "leafy",
    unit: "100g",
    variant: "Fresh",
    pricePerUnit: 25,
    originalPrice: 40,
    stockQuantity: 120,
    harvestDate: "2026-01-21",
    expiry: "2026-01-24",
    nameSeller: "Herb Garden",
    typeSeller: "Local Grower",
    image: "🌿",
    description: "Aromatic coriander for garnishing and cooking."
  },
  {
    id: 7,
    name: "Fenugreek Leaves (Methi)",
    category: "leafy",
    unit: "250g",
    variant: "Fresh",
    pricePerUnit: 35,
    originalPrice: 55,
    stockQuantity: 70,
    harvestDate: "2026-01-19",
    expiry: "2026-01-26",
    nameSeller: "Green Patch",
    typeSeller: "Small Farmer",
    image: "🌱",
    description: "Nutritious methi leaves with a mild bitter taste."
  },
  {
    id: 8,
    name: "Organic Finger Millet (Ragi)",
    category: "millets",
    unit: "1kg",
    variant: "Organic",
    pricePerUnit: 110,
    originalPrice: 160,
    stockQuantity: 50,
    harvestDate: "2025-12-20",
    expiry: "2026-06-20",
    nameSeller: "Millet Trust",
    typeSeller: "Organic Cooperative",
    image: "🌾",
    description: "High-calcium ragi millet for healthy diets."
  },
  {
    id: 9,
    name: "Pearl Millet (Bajra)",
    category: "millets",
    unit: "1kg",
    variant: "Natural",
    pricePerUnit: 95,
    originalPrice: 140,
    stockQuantity: 65,
    harvestDate: "2025-12-18",
    expiry: "2026-06-18",
    nameSeller: "Desi Grains",
    typeSeller: "Farmer Group",
    image: "🌾",
    description: "Energy-rich bajra suitable for rotis and porridge."
  },
  {
    id: 10,
    name: "Foxtail Millet",
    category: "millets",
    unit: "1kg",
    variant: "Organic",
    pricePerUnit: 130,
    originalPrice: 180,
    stockQuantity: 40,
    harvestDate: "2025-12-22",
    expiry: "2026-06-22",
    nameSeller: "Healthy Harvest",
    typeSeller: "Organic Producer",
    image: "🌾",
    description: "Low-GI millet ideal for weight management."
  },

  /* ---- Cereals ---- */
  {
    id: 11,
    name: "Whole Wheat Grains",
    category: "cereals",
    unit: "5kg",
    variant: "Natural",
    pricePerUnit: 280,
    originalPrice: 350,
    stockQuantity: 30,
    harvestDate: "2025-11-30",
    expiry: "2026-11-30",
    nameSeller: "Golden Fields",
    typeSeller: "Grain Supplier",
    image: "🌾",
    description: "Unpolished whole wheat grains for flour milling."
  },
  {
    id: 12,
    name: "Raw Rice",
    category: "cereals",
    unit: "5kg",
    variant: "Premium",
    pricePerUnit: 320,
    originalPrice: 400,
    stockQuantity: 25,
    harvestDate: "2025-12-05",
    expiry: "2026-12-05",
    nameSeller: "Rice Bowl",
    typeSeller: "Rice Mill",
    image: "🍚",
    description: "Premium raw rice suitable for daily meals."
  },
  {
    id: 13,
    name: "Brown Rice",
    category: "cereals",
    unit: "1kg",
    variant: "Organic",
    pricePerUnit: 110,
    originalPrice: 150,
    stockQuantity: 55,
    harvestDate: "2025-12-10",
    expiry: "2026-12-10",
    nameSeller: "Health Grains",
    typeSeller: "Organic Supplier",
    image: "🍚",
    description: "Fiber-rich brown rice for healthier eating."
  },

  /* ---- Eggs ---- */
  {
    id: 14,
    name: "Country Chicken Eggs",
    category: "eggs",
    unit: "12 pcs",
    variant: "Free Range",
    pricePerUnit: 180,
    originalPrice: 220,
    stockQuantity: 40,
    harvestDate: "2026-01-20",
    expiry: "2026-02-05",
    nameSeller: "Happy Hen Farm",
    typeSeller: "Poultry Farmer",
    image: "🥚",
    description: "Nutritious free-range country eggs."
  },
  {
    id: 15,
    name: "White Eggs",
    category: "eggs",
    unit: "12 pcs",
    variant: "Farm Fresh",
    pricePerUnit: 140,
    originalPrice: 180,
    stockQuantity: 60,
    harvestDate: "2026-01-21",
    expiry: "2026-02-06",
    nameSeller: "Egg Basket",
    typeSeller: "Poultry Supplier",
    image: "🥚",
    description: "Fresh white eggs rich in protein."
  },

  /* ---- Meat ---- */
  {
    id: 16,
    name: "Fresh Chicken Breast",
    category: "meat",
    unit: "500g",
    variant: "Antibiotic-Free",
    pricePerUnit: 220,
    originalPrice: 260,
    stockQuantity: 35,
    harvestDate: "2026-01-21",
    expiry: "2026-01-24",
    nameSeller: "Clean Meat Co.",
    typeSeller: "Meat Supplier",
    image: "🍗",
    description: "Lean chicken breast with no added hormones."
  },
  {
    id: 17,
    name: "Goat Curry Cut",
    category: "meat",
    unit: "500g",
    variant: "Fresh Cut",
    pricePerUnit: 450,
    originalPrice: 520,
    stockQuantity: 20,
    harvestDate: "2026-01-20",
    expiry: "2026-01-23",
    nameSeller: "Desi Meats",
    typeSeller: "Butcher Shop",
    image: "🥩",
    description: "Tender goat meat ideal for curries."
  },

  /* ---- Continue Mixed Items ---- */
  {
    id: 18,
    name: "Organic Drumstick",
    category: "vegetables",
    unit: "250g",
    variant: "Organic",
    pricePerUnit: 60,
    originalPrice: 90,
    stockQuantity: 50,
    harvestDate: "2026-01-18",
    expiry: "2026-01-28",
    nameSeller: "Village Greens",
    typeSeller: "Organic Farmer",
    image: "🥒",
    description: "Fresh drumsticks rich in nutrients."
  },
  {
    id: 19,
    name: "Little Millet",
    category: "millets",
    unit: "1kg",
    variant: "Organic",
    pricePerUnit: 125,
    originalPrice: 170,
    stockQuantity: 45,
    harvestDate: "2025-12-25",
    expiry: "2026-06-25",
    nameSeller: "Pure Millets",
    typeSeller: "Organic Producer",
    image: "🌾",
    description: "Light and nutritious little millet."
  },
  {
    id: 20,
    name: "Fresh Mutton Liver",
    category: "meat",
    unit: "250g",
    variant: "Fresh",
    pricePerUnit: 180,
    originalPrice: 220,
    stockQuantity: 15,
    harvestDate: "2026-01-21",
    expiry: "2026-01-23",
    nameSeller: "Prime Cuts",
    typeSeller: "Local Butcher",
    image: "🥩",
    description: "Iron-rich fresh mutton liver."
  }
];
export default data