# Generated by Django 5.2.10 on 2026-02-04 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=70)),
                ('mrp', models.IntegerField()),
                ('min_price', models.IntegerField()),
                ('current_price', models.IntegerField()),
            ],
        ),
    ]
