# Generated by Django 5.2.10 on 2026-02-08 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AI_Negotiaton', '0002_negotiationhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductDetails',
        ),
    ]
